module.exports = {
    FETCH_TIMEOUT: 10000,
    STATUS_DAY_CLOSED: "Cerrado",
    STATUS_DAY_OPENED: "Abierto",
    STATUS_DAY_NODATA: "Sin Datos",
    ERROR_CREDENCIALES_INVALIDAS: 1001,
    ERROR_SIN_CONEXION: 1002,
    ERROR_TIMEOUT: 1003
}